[package]
name = "structible"
edition = "2024"
description = "Define structs backed by HashMap or BTreeMap with generated accessors"
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
structible-macros = { version = "0.1.0", path = "../structible-macros" }
