[package]
name = "structible"
version = "0.1.0"
edition = "2021"
description = "Define structs backed by HashMap or BTreeMap with generated accessors"
license = "MIT"
repository = "https://github.com/eikopf/structible"
readme = "README.md"

[dependencies]
structible-macros = { version = "0.1.0", path = "../structible-macros" }
